
--------------------begin------------------------

[2020/03/17 15:32:02.903675][i][e1438693f] oms-api 正在退出...
[2020/03/17 15:32:03.334058][i][e1438693f] oms-api 已安全退出

---------------------end-------------------------

--------------------begin------------------------

[2020/03/17 15:33:35.924326][i][ffa3bd35f] Connected to 192.168.0.101:2181
[2020/03/17 15:33:35.939402][i][ffa3bd35f] authenticated: id=103610669116165536, timeout=4000
[2020/03/17 15:33:35.939417][i][ffa3bd35f] re-submitting `0` credentials after reconnect
[2020/03/17 15:33:35.976158][i][ffa3bd35f] 初始化 /oms_t_debug/omsadmin/api/5.62
[2020/03/17 15:33:35.915163][i][3dcc59118] 开始启动[API]服务...
[2020/03/17 15:33:35.915267][e][3dcc59118] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------
